no-dev-version = true
pre-release-commit-message = "release {{crate_name}} {{version}}"
disable-tag = true
disable-push = true
disable-publish = true
enable-features = ["all", "twitch_oauth2/all", "unsupported"]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="v{{version}}", prerelease=false},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", prerelease=false},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate\n\n[Commits](https://github.com/Emilgardis/twitch_api2/compare/{{version}}...Unreleased)", prerelease=false},
  {file="README.md", search="twitch_api2/[a-z0-9\\.-]+/twitch_api2", replace="{{crate_name}}/{{version}}/{{crate_name}}"},
  {file="src/lib.rs", search="https://docs.rs/twitch_api2/[a-z0-9\\.-]+", replace="https://docs.rs/{{crate_name}}/{{version}}"},
  {file="Cargo.toml", search="https://docs.rs/twitch_api2/[a-z0-9\\.-]+", replace="https://docs.rs/{{crate_name}}/{{version}}"},
]